const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const os = require('node:os');
const {chromium} = require('playwright');
const docs = path.resolve(__dirname, '../docs');
const artifacts = path.join(os.tmpdir(), 'vantage-market-qa');
fs.mkdirSync(artifacts, {recursive:true});
const server = http.createServer((req,res) => {
  const pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
  const file = path.resolve(docs, '.' + pathname);
  if (!file.startsWith(docs + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404);res.end();return; }
  res.setHeader('Content-Type', ({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json'})[path.extname(file)] || 'application/octet-stream');
  fs.createReadStream(file).pipe(res);
});
(async()=>{
  let browser;
  try {
    await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
    const base=`http://127.0.0.1:${server.address().port}`;
    browser=await chromium.launch({headless:true,channel:'msedge'});
    const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
    await context.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
    const page=await context.newPage();
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(base+'/bottomup.html#map');
    await page.locator('#__gate_input').fill('1011'); await page.locator('#__gate_btn').click();
    await page.waitForSelector('.sb-card');
    await page.waitForFunction(()=>document.querySelector('.sb-card .sb-chart svg'));
    assert.equal(await page.locator('.sb-card').count(),12);
    await page.locator('[data-p="vol"]').click();
    await page.waitForFunction(()=>document.querySelector('#sb-sort [data-s="vol"]').getAttribute('aria-pressed')==='true');
    assert.match(await page.locator('.sb-card').first().innerText(),/거래대금/);
    await page.locator('[data-p="pat"]').click();
    assert.equal(await page.locator('#sb-sort .on').getAttribute('data-s'),'breakout');
    await page.locator('.sb-card').first().scrollIntoViewIfNeeded();
    await page.waitForSelector('.sb-card .sb-chart svg');
    assert.match(await page.locator('.sb-card').first().innerText(),/돌파/);
    await page.locator('#sb-sort [data-s="momentum"]').click();
    assert.match(await page.locator('#sb-sort-note').innerText(),/20%.*30%.*50%/);
    await page.locator('.sb-card').first().scrollIntoViewIfNeeded();
    await page.waitForSelector('.sb-card .sb-chart svg');
    await page.screenshot({path:path.join(artifacts,'signals-desktop.png')});
    await page.locator('.sb-open-detail').first().click();
    await page.waitForSelector('#modal-back .m-body svg');
    await page.keyboard.press('Escape');
    await page.locator('#sb-reset').click();
    const before=await page.locator('.sb-card').count();
    await page.locator('#sb-more').click();
    assert.equal(await page.locator('.sb-card').count(),before+12);
    await page.locator('#q').fill('no-such-stock-xyz');
    await page.waitForSelector('#signal-board .empty-note');
    await page.locator('#sb-reset').click();
    await page.locator('#sb-sort [data-s="breakout"]').click();
    await page.locator('.pane-tab[data-pane="list"]').click();
    assert.equal(await page.locator('#sort-toggle .on').getAttribute('data-s'),'breakout');
    await page.locator('.pane-tab[data-pane="pattern"]').click();
    await page.locator('.pt-card').first().scrollIntoViewIfNeeded();
    await page.waitForSelector('.pt-card svg');
    await page.locator('.pane-tab[data-pane="map"]').click();
    await page.setViewportSize({width:390,height:844});
    await page.locator('.sb-card').first().scrollIntoViewIfNeeded();
    await page.waitForTimeout(250);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'signal mobile overflow');
    await page.screenshot({path:path.join(artifacts,'signals-mobile.png')});

    await page.setViewportSize({width:1440,height:1100});
    await page.goto(base+'/dashboard.html#trend');
    await page.waitForSelector('#trend-chart svg');
    assert.equal(await page.locator('.dashboard-panes .pane-tab').count(),2);
    assert.equal(await page.locator('.dashboard-panes > .pane').count(),2);
    for(const id of ['flow-year','flow-signals','flow-trend','flow-heatmap']) assert.equal(await page.locator('#'+id).isVisible(),true,id+' visible');
    await page.locator('.pane-tab[data-pane="compare"]').click();
    await page.waitForSelector('#etf-table tbody tr');
    await page.locator('.pane-tab[data-pane="flow"]').click();
    await page.locator('#flow-year').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(artifacts,'sectors-desktop.png')});
    await page.setViewportSize({width:390,height:844});
    await page.waitForTimeout(250);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'dashboard mobile overflow');
    await page.screenshot({path:path.join(artifacts,'sectors-mobile.png')});

    await page.setViewportSize({width:1440,height:1100});
    await page.goto(base+'/macro.html');
    await page.waitForFunction(()=>document.querySelectorAll('#mx-watch .mx-watch-value').length===3);
    assert.equal(await page.locator('#mx-watch article').count(),3);
    const titles=await page.locator('#mx-watch h2').allTextContents();
    assert.match(titles[0],/공포|Fear/);assert.match(titles[1],/국채/);assert.match(titles[2],/WTI/);
    assert.match(await page.locator('#mx-watch article').first().innerText(),/프록시/);
    assert.equal(await page.locator('#mx-watch svg').count(),3);
    assert.equal(await page.evaluate(()=>document.querySelector('#mx-watch').offsetTop<document.querySelector('#mx-rates-section').offsetTop&&document.querySelector('#mx-rates-section').offsetTop<document.querySelector('[aria-label="경제 캘린더"]').offsetTop),true);
    await page.screenshot({path:path.join(artifacts,'macro-desktop.png')});
    await page.locator('[data-watch-ind="wti"]').click();
    await page.waitForSelector('.mx-row[data-k="wti"].open');
    await page.setViewportSize({width:390,height:844});
    await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(250);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'macro mobile overflow');
    await page.screenshot({path:path.join(artifacts,'macro-mobile.png')});
    await page.route('**/macro.json',route=>route.fulfill({status:503,body:'unavailable'}));
    await page.reload();
    await page.waitForFunction(()=>document.querySelector('#mx-watch article').textContent.includes('불러오지 못했습니다'));
    assert.equal(await page.locator('#mx-watch .mx-watch-value').count(),2,'independent macro failure preserves other cards');
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({result:'PASS',checks:['signal preset and automatic sort','momentum explanation','candles and modal','pagination','empty and reset','rank sort sync','pattern candles','two sector panes and legacy hash','comparison table','macro first-screen order and real charts','oil detail','macro partial failure','desktop and mobile overflow','no page errors'],artifacts}));
    await context.close();
  } finally { if(browser)await browser.close();server.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
